modules = ["python-3.11", "python3"]

[nix]
channel = "stable-24_05"

[deployment]
deploymentTarget = "autoscale"
run = ["sh", "-c", "PYTHONPATH=/home/runner/workspace streamlit run frontend/main.py"]

[workflows]
runButton = "Project"

[[workflows.workflow]]
name = "Project"
mode = "parallel"
author = "agent"

[[workflows.workflow.tasks]]
task = "workflow.run"
args = "Streamlit App"

[[workflows.workflow.tasks]]
task = "workflow.run"
args = "FastAPI Server"

[[workflows.workflow]]
name = "Streamlit App"
author = "agent"

[workflows.workflow.metadata]
agentRequireRestartOnSave = false

[[workflows.workflow.tasks]]
task = "packager.installForAll"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "PYTHONPATH=/home/runner/workspace streamlit run frontend/main.py"
waitForPort = 5000

[[workflows.workflow]]
name = "FastAPI Server"
author = "agent"

[workflows.workflow.metadata]
agentRequireRestartOnSave = false

[[workflows.workflow.tasks]]
task = "packager.installForAll"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "PYTHONPATH=/home/runner/workspace python3 backend/api/document_processor_service.py"
waitForPort = 8002

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 8000
externalPort = 8000

[[ports]]
localPort = 8001
externalPort = 3000

[[ports]]
localPort = 8002
externalPort = 3001
